services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: rocketlog

  migrate:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/rocketlog
    command: npx prisma migrate deploy
    depends_on:
      - postgres
